---

- name: Load Jenkinsfile content into memory
  set_fact:
    jenkins_test_files: "{{ jenkins_test_files|default([]) + [{'path': item, 'content': lookup('file', '{{ item }}') }] }}"
  with_items: "{{ lookup('fileglob', '{{ clone_dir }}/test/Jenkinsfile-*', wantlist=true) }}"
